defaults: []
seed: 42
llm_model_source: "openai"
llm_model_name: "gpt-3.5-turbo"
retriever_type: "dense"
embedding_model_source: "huggingface"
embedding_model_name: "BAAI/bge-m3"
chat_template: |
  Answer the user's question using only the provided information below:
  {docs}
